### PR TITLE
Remove volume slider timer.

### PR DESCRIPTION
**Pull request by jcass77**
This PR contains a few optimisations for the volume slider:

- use ``localStorage`` to sync volume changes between browser windows
- listen for Mopidy's ``volumeChanged`` events instead of using the timer. The more frequent updates that this results in should make it easier for users to select the exact volume level that they are looking for.

Removing the timer also means that we will no longer interfere with what other extensions are doing - see #162.

### CODE REVIEW

**Comment by dublok** [comment]
Before you merge: please recheck.
On raspbian with the `midori` browser the volume slider is zero at start (same for the raspbian default `Webbrowser`). And the slider does not move for every volume change.

I also get error messages from midori:
```
** Message: console message: http://localhost:6680/mopidy/mopidy.min.js @5: TypeError: event:volumeChanged listener threw error: null is not an object (evaluating 'localStorage.getItem')
```
(I had to enable HTLM5 local storage, cleared cache, reload page, but nothing helped)

**Comment by jcass77** [comment]
Please try again with 797b75839708f80938170360ef68d07b0d8f5f93, which should fix the TypeError.

[midori-browser.org](http://midori-browser.org) seems to be down at the moment (!?) so I can't test this directly.

Could you please clarify what is meant by *'And the slider does not move for every volume change'*? If you are setting the volume programatically using HTTP RPC and lots of rapid-fire changes, then in theory it is still possible that the client can miss some of them as it has to wait for the slider to sync up with every change event.

That being said, I had no issues testing rapid fire changes using the following script:

```
#!/usr/bin/python


import time
import requests


# http requests
def change_volume(increment):
    get_volume = { 'method': 'core.mixer.get_volume',
            'jsonrpc': '2.0', 'params': {}, 'id': 1}
    r = requests.post('http://localhost:6680/mopidy/rpc', json = get_volume)
    if r.status_code == requests.codes.ok:
        r_json = r.json()
        if 'result' in r_json:
            volume = r_json['result']

            if increment:
                volume += 3
            else:
                volume -= 3

            if volume < 0:
                volume = 0
            if volume > 100:
                volume = 100

            set_volume = { 'method': 'core.mixer.set_volume',
                    'jsonrpc': '2.0', 'params': {'volume': volume}, 'id': 1}
            r = requests.post('http://localhost:6680/mopidy/rpc', json = set_volume)
            if r.status_code != requests.codes.ok:
                print('error: can\'t set mopidy volume: ' + r.text)
            else:
                print('set mopidy volum to %i' %volume)
    else:
        print('error: can\'t get volume from mopdy: ' + r.text)


i = 0
while i < 20:
    i += 1
    change_volume(False)
    # time.sleep(0.05)
```

Midori does not appear to score particularly well on HTML5 tests, so this issue might be browser-specific. (see https://html5test.com/s/e5f65e2cf36e22e9.html).

**Comment by dublok** [comment]
At raspbian:
With 797b758 it is still not working. The error message is gone, but the silder is out-of-order.
- When starting the browser, the slider shows zero (mopidy volume is 50)
- Moving the sliding does not set the mopidy volume (browsing tracks is working)
- same error for both lightweight browser: midori, ephiphany
At Ubuntu:
- working: midori, firefox

I use a rotary encoder to set the volume. (The volume_setter.py is part of the script.)
'And the slider does not move' mean: 
- turn volume up (20..80), 
- wait
- turn donw (80..40), 
- wait
- turn up(40..70), 
- ah, now the slider moved from 0 to 70.

Currently the slider does not move if mopdy changes the volume (raspbian). I am still searching if something with my RPi configuration is wrong.

Is it possible to avoid localStorage?

**Comment by dublok** [comment]
Mopidy 2.0 

More tests:
- mopidy running on Ubuntu, 
  1. browser on Ubuntu
    - firefox OK
    - midory OK
  2. browser on Raspbian
    - icewesel(firefox) OK
    - midory ERROR_A

- mopidy running on raspberry
  1. browser on Ubuntu
    - firefox ERROR_B
    - midory ERROR_B
  2. browser on Raspbian
    - icewesel(firefox) ERROR_B
    - midory ERROR_B


ERROR_A
        - The volume slider is initialized correct
        - the slider does not move if mopidy changes the volume
        - moving the slider does not change mopidies volume

ERROR_B
        - The volume slider is initialized to zero
        - the slider does not move if mopidy changes the volume
        - moving the slider does not change mopidies volume

**Comment by jcass77** [comment]
I can't imagine why running Mopidy on Ubuntu would produce a different result compared the same test with Mopidy running on the Raspberry Pi.

I've tested this with Safari, Firefox, and Chrome with Mopidy running on Max OS X and Raspberry Pi - all working.

I just noticed that you are using Mopidy 2.0? There isn't a stable release for that yet as far as I know so it is likely that there may be other issues with the event triggers that are not related to the web client?

**Comment by jcass77** [comment]
Would you mind testing with Mopidy 1.1.2 and report back if the problem persists?

**Comment by dublok** [comment]
OK. Back to the roots.

mopidy on RPi: 
```
pi@pimusic ~/Documents/mopidy $ git log -n1
commit 2ba5bdc82274ac9975257321a490419c72dcde84
Merge: 25bd134 6d0e3ec
Author: Stein Magnus Jodal <stein.magnus@jodal.no>
Date:   Mon Jan 18 22:54:57 2016 +0100

    Release v1.1.2
```
```
pi@pimusic ~/Documents/mopidy-musicbox-webclient $ git log -n1
commit 797b75839708f80938170360ef68d07b0d8f5f93
Author: jcass <john.cass77@gmail.com>
Date:   Sat Feb 13 13:48:25 2016 +0200

    Fix Javascript type error.
```
midori/Ubuntu and midori/Raspbian 
-> slider not working -> ERROR_B

firefox/Ubuntu and iceweasel/Raspbian 
-> ERROR_C 
slider start at zero, 'And the slider does not move for every volume change', moving the slider does not change the volume)

**Comment by dublok** [comment]
Same versions for mopidy and musicbox-webclient as in the last comment.

mopidy running on Ubuntu.

midori/firefox Ubuntu
-> working

iceweasel/Raspbian
- slider working
- !! feedback loop !! setting volume endless 62 65 62 65 ...

midori/Raspbian
-> ERROR_B


Intermediate result:
- midori has an issue (probably with the localStorage)
- my mopidy installations on Raspbian and Ubuntu behave different
  - different extension (to investigate)
  - different operating system and python library versions 
  - timing?

**Comment by jcass77** [comment]
Thank you for the feedback. It's difficult to troubleshoot this one unless we can get to the root cause of why the different operating systems and browsers are behaving differently for you.

I'm guessing that all of these are just variations on two issues:

1. ``localStorage`` either not being enabled or supported for some of the browsers.
2. the event triggers somehow not reaching the web client from your Pi. Have you played around with the ``websocket_host`` and ``websocket_port`` configuration settings? I'd also try replacing ``localhost`` with the full IP address in the scripts that you are using, as well as in the browser URL.

What happens when you run the same tests using another web client with comparable features ([Mopidy-Mobile](https://github.com/tkem/mopidy-mobile) might be a good choice).

**Comment by dublok** [comment]
I also tested an older version of the webclient. And every combination of browser/operating system is working. 
```
pi@pimusic ~/Documents/mopidy-musicbox-webclient $ git log -n1
commit a65c5409e474ee47dc10d6498e7bb123376b4cb2
Merge: 420a545 28c8cc6
Author: Nick Steel <nsteel@fastmail.com>
Date:   Mon Feb 8 20:45:15 2016 +0000

    Merge branch 'jcass77-fix/157_landscape_screen_scaling' into develop
```


One remark for testing web page changes: to make the browser show the updated page I have to:
- stop/start mopidy
- clear browser cache and local storage
- reload page

**Comment by dublok** [comment]
The http config is the same on both systems:
```
[http]
enabled = true
hostname = ::
port = 6680
static_dir =
zeroconf = Mopidy HTTP server on $hostname
```
The mpd config is different
Raspbian:  
```
[mpd]
hostname = ::
```
Ubuntu:  
```
[mpd]
hostname = 127.0.0.1
```

And I am using the alsamixer on Raspbian:
```
[audio]
mixer = alsamixer
mixer_volume = 
output = alsasink

[alsamixer]
enabled = true
card = 0
control = PCM
```

**Comment by dublok** [comment]
One comment to the behaviour of the webclient:
- mopidy send a volume change to the webclient
- the webclient send the changed volume back to mopidy

From my point of view 'sending volume back to mopidy' is a bit unexpected. I have no idea if and how to suppress that on webclient side. Can the slider differ between 'moving the slider' and 'set a value to the slider'?

**Comment by dublok** [comment]
Using `mixer = software` and/or `mpd/hostname = 127.0.0.1` on Raspbian make no difference: slider not working with midori/Raspbian.

**Comment by dublok** [comment]
I don't get mopidy-mobile to run, but that's a different issue. (or a hint to a problem with my Raspbian installation) 

Runtime error if installed via pip:
I`OError: [Errno 2] No such file or directory: u'/usr/local/lib/python2.7/dist-packages/mopidy_mobile/www/app/playback/playback.html'`

Can't install from source:
```
pi@pimusic ~/Documents/mopidy-mobile $ sudo pip install --editable .
Obtaining file:///home/pi/Documents/mopidy-mobile
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/pi/Documents/mopidy-mobile/setup.py", line 8, in <module>
        assert os.path.exists('mopidy_mobile/www/mopidy-mobile.bundle.min.js')
    AssertionError
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/pi/Documents/mopidy-mobile
```

**Comment by jcass77** [comment]
Could you try browsing to http://jsfiddle.net/bmknight/WjHTX/ in Midori? This should tell you if it supports ``localStorage`` or not.

On sending the volume change back to Mopidy: this should just happen the first time that the web client is initialised, but I've added an optimisation in https://github.com/jcass77/Mopidy-MusicBox-Webclient/commit/72a2dbf13c5116d0180a1b766a95fae7d99f0bad so that this is no longer the case.

I also switched from the pure Javascript ``bind`` event listener to jQuery's ``on`` listeners - just in case this improves the situation for you - let me know how it goes...

**Comment by dublok** [comment]
Bad news for local stoarge support.
Midori/Raspbian don't like the page. And I get similar error message on the shell:
```
** Message: console message: http://fiddle.jshell.net/bmknight/WjHTX/show/ @79: TypeError: null is not an object (evaluating 'localStorage.getItem')
```

**Comment by dublok** [comment]
Sorry, but no improvement with 72a2dbf13c5116d0180a1b766a95fae7d99f0bad. The slider is not working. Tested: firefox/Ubuntu, midori/Ubuntu, midori/Raspbian.

Maybe we have to stop here investigating the issue.
Maybe I have to setup my RPi from scratch.

**Comment by dublok** [comment]
mopidy/Ubuntu
- firefox/Ubuntu: working
- midori/Ubuntu: working
- midori/Ubuntu (disabled localStoara): not working

**Comment by jcass77** [comment]
Let's try one more: https://github.com/pimusicbox/mopidy-musicbox-webclient/commit/b04413c61b5199880a2da6c57df3c85be1bbf543 removes the reliance on ``localStorage``, replacing it with a global variable.

It should work just as well, except if the user has multiple browser windows open all running the web client.

**Comment by jcass77** [comment]
@kingosticks, do you want to give this a whirl before we merge?

I've tested it with Chrome, Safari (and OS), and Firefox all running concurrently and each having two browser windows open that point to Musicbox-Webclient. Also tested with Mopidy running on the Raspberry Pi and Mac OS, and even triggered a large number of volume change events using the script referenced above - seems to be working in every instance.

With ``localStorage`` removed we should now also be able to support the same set of legacy browser versions as before.

**Comment by dublok** [comment]
Much better. Thank you. The slider is working as expected.
One new issue: midori and firefox: after touching the slider, holding it and moving it, it does not send volume updates.

**Comment by jcass77** [comment]
I can't seem to reproduce that issue unfortunately. The only way to track it down on your setup may be to use the Firefox developer tools, and set breakpoints at a few relevant places in the source code:

- updating the track slider: https://github.com/jcass77/Mopidy-MusicBox-Webclient/blob/461e54d5bdeb9e0086011bf92dd79d2b1dd0d3ec/mopidy_musicbox_webclient/static/js/controls.js#L402

- processing volume changes when the slider moves: https://github.com/jcass77/Mopidy-MusicBox-Webclient/blob/461e54d5bdeb9e0086011bf92dd79d2b1dd0d3ec/mopidy_musicbox_webclient/static/js/controls.js#L410

- responding to volume change events sent by Mopidy: https://github.com/jcass77/Mopidy-MusicBox-Webclient/blob/461e54d5bdeb9e0086011bf92dd79d2b1dd0d3ec/mopidy_musicbox_webclient/static/js/gui.js#L268

**Comment by kingosticks** [comment]
I think I'm confident that with all this between you guys it's tested sufficiently.

**Comment by dublok** [comment]
'Slider stops working' is still reproducible ab5369467bafd65c2ebcf1657d855ccbcd60d05b:
- mopidy on raspberry
- firefox/ubuntu
- click on the slider and hold mouse button down
- move forward and backward (with button down)
- > if moved to fast for-back-for-back... it stops working. Seems to be timing issue.

I'll have a look into the firefox develop tools...

**Comment by dublok** [comment]
I add a bit debug code: [logout.diff.zip](https://github.com/pimusicbox/mopidy-musicbox-webclient/files/129775/logout.diff.zip)
```
function setVolume(value) {
       console.info("setVolume", volumeChanging, $("#volumeslider").val(), value);

function doVolume(value) {
       console.info("doVolume", volumeChanging, value);

mopidy.on("event:volumeChanged", function(data) {
       console.info("volumeChanged", volumeChanging, data["volume"]);
```
and the slider stopped working very fast:
```
http://pimusic.local/mopidy/ws [HTTP/1.1 101 Switching Protocols 19ms]
setVolume undefined 0 40 controls.js:378:1
GET 
http://pimusic.local/images/581237907d7b327a202463adbd8be524-640x640.jpeg [HTTP/1.1 304 Not Modified 39ms]
doVolume undefined 37 controls.js:387:2
volumeChanged 37 37 gui.js:260:6
setVolume null 37 37 controls.js:378:1
doVolume null 36 controls.js:387:2
doVolume 36 35 controls.js:387:2
doVolume 36 34 controls.js:387:2
volumeChanged 36 36 gui.js:260:6
setVolume null 34 36 controls.js:378:1
doVolume null 34 controls.js:387:2
doVolume 34 33 controls.js:387:2
doVolume 34 32 controls.js:387:2
volumeChanged 34 34 gui.js:260:6
setVolume null 32 34 controls.js:378:1
doVolume null 31 controls.js:387:2
doVolume 31 31 controls.js:387:2
volumeChanged 31 31 gui.js:260:6
setVolume null 31 31 controls.js:378:1
doVolume null 31 controls.js:387:2
doVolume 31 30 controls.js:387:2
doVolume 31 29 controls.js:387:2
doVolume 31 27 controls.js:387:2
doVolume 31 28 controls.js:387:2
doVolume 31 29 controls.js:387:2
doVolume 31 31 controls.js:387:2

```

**Comment by jcass77** [comment]
0d54984f3850dd73e44f2f4aac1de52753160b75 blocks Mopidy's ``volumeChanged`` events from triggering a slider update while the user is busy dragging the slider - might improve the situation for you.

**Comment by jcass77** [comment]
@dublok, #168 might explain the issues that you are having on the Pi (if you're using ALSA mixer).

**Comment by dublok** [comment]
@jcass77: Thanks for the hint. Now the volume slider is working perfect. 
And thanks for the legacy browser support. It saves me from using iceweasel on the pi.

**Pull request merged**
