### PR TITLE
Adding version info to home page

### PR DESCRIPTION
**Pull request by fmarzocca**
I thought it was useful to have musicbox version info on web Home Page (right after the host informations).

### CODE REVIEW

**Comment by fmarzocca** [comment]
Changes has been applied to move the version label at the bottom.

**Comment by kingosticks** [comment]
Please remember that Mopidy-Pimusicbox-Webclient is a generic Mopidy webclient that can be installed on any system. It is also used in PiMusicbox. I still think this information is only interesting for debug, you don't need to see it all the time. It seems weird to have a generic Mopidy webclient display the *system* version. I assumed you were going to display the webclient version.

**Comment by kingosticks** [comment]
And what happens on those other systems where /etc/issue doesn't exist?

**Comment by fmarzocca** [comment]
>  I assumed you were going to display the webclient version.

where is the webclient version?

**Comment by kingosticks** [comment]
You can get it from https://github.com/pimusicbox/mopidy-musicbox-webclient/blob/develop/mopidy_musicbox_webclient/webclient.py#L20

**Pull request closed without merging**
