### PR TITLE
Refactor code for displaying track lists.

### LINKED ISSUE #99: Track artist is not displayed in browse results
Originally posted at https://discuss.mopidy.com/t/artist-name-not-displayed-in-several-screens/682

>I'm just in the process of upgrading from musicbox 0.53 to 0.6 and noticed that the artist name is no longer displayed in the "Queue" screen. 
While I quite like the additional line showing the album name and album artist, the individual artists of the tracks are missing. This makes identifying the songs rather difficult.

### LINKED ISSUE #126: Can't use contextmenu in browse pane
Nothing happens, when I click on the 3dot-button. Is this a common issue and does somebody know what the problem is? I'm on version 0.6 and didn't upgrade the webclient or something like that.

### PR DESCRIPTION
**Pull request by jcass77**
This PR represents the start of an effort to consolidate how lists of tracks are retrieved and displayed in the UI:

- fixes an issue that caused the popup menu in the browse pane to render differently than the others, or not at all. Fixes #126.
- further refactoring of ``renderSongLi``. There's more work to be done here as the various ``play...`` functions can also probably be refactored and consolidated. I'd eventually like to get to a point where we only have one list of tracks that can be cached and used in all of the panes. But that is a PR for another day.
- fixed a small issue with the default images for artists and albums sometimes not displaying if they cannot be retrieved from last.fm.
- browsing using the ``local`` or ``file`` extensions will now also render album and artist details, which fixes #99. It works well but the performance impact is noticeable for lists containing more than a hundred tracks or so. We might eventually either make this a configuration setting, or include a button on-screen that the user can use to toggle the details for any ``TrackRefs``. Ultimately, this could also be used to sort by artist or album on the fly. 

The rules for displaying album details are currently as follows:
1. if we only have one track in the list, then show its album details
2. if we have more than one consecutive track from the same album, then add an album header above the tracks. Album details are not repeated for each of the album's tracks.
3. if we do not have any album info available or consecutive tracks are from different albums, then display a think grey divider between the tracks.

This PR also paves the way for fixing #69 and #96.

### CODE REVIEW

**Comment by jcass77** [comment]
Just a note that I have pushed some more change which ensures that the loading popup is displayed until after all of the album details have been retrieved.

Also fixes an issue where the album details for the first track in the list was not being rendered.

**Comment by jcass77** [comment]
I've pushed https://github.com/pimusicbox/mopidy-musicbox-webclient/commit/a00754dd389139fec1812687f7092e852e359b4c which ensures that each track name is proceeded with an icon (except if part of a multi-track album) and a space character.

**Comment by jcass77** [comment]
https://github.com/jcass77/Mopidy-MusicBox-Webclient/commit/60041c142ed62e5134cdc0bf19b219488b463abf refactors and consolidates how the 'Back' button is rendered at the top of track lists, and how messages are displayed when a folder does not contain any tracks.

https://github.com/jcass77/Mopidy-MusicBox-Webclient/commit/1c1fbee137a3cb5c3a466c215e9589bcf04cbe0b makes it more obvious if searches came up empty by showing 'No tracks found...' in the results table.

I'll run a few more tests and merge this tomorrow (Sunday) morning if there are no further inputs from anyone.

**Comment by kingosticks** [comment]
I'm away this weekend so I cannot try this.

**Comment by jcass77** [comment]
https://github.com/pimusicbox/mopidy-musicbox-webclient/commit/5437205e4df51eece55d5034bbe11a73799b5d10 optimises the jQuery selectors to use identifiers instead of attributes. Lists with roughly 2 000 tracks are now rendered about 80 times faster.

Also fixed a small issue with play icons not being updated in the ``#albumstable``, and replaced string references with their JavaScript constants.

**Comment by jcass77** [comment]
I've been using this for a few days without any apparent issues. I'll merge later tonight if there are no objections.

**Pull request merged**
