### PR TITLE
Ignore calls to locationHashChanged untill page has finished loading

### LINKED ISSUE #230: Exception when refreshing the Album and Artist pages
```
Uncaught TypeError: Cannot read property 'library' of undefined
    at Object.showArtist (http://localhost:6681/musicbox_webclient/js/library.js:281:19)
    at locationHashChanged (http://localhost:6681/musicbox_webclient/js/gui.js:402:25)
    at Object.trigger (http://localhost:6681/musicbox_webclient/vendors/jquery/jquery-1.12.0.min.js:3:11522)
    at http://localhost:6681/musicbox_webclient/vendors/jquery/jquery-1.12.0.min.js:3:18895
    at Function.each (http://localhost:6681/musicbox_webclient/vendors/jquery/jquery-1.12.0.min.js:2:2881)
    at n.fn.init.each (http://localhost:6681/musicbox_webclient/vendors/jquery/jquery-1.12.0.min.js:2:846)
    at n.fn.init.trigger (http://localhost:6681/musicbox_webclient/vendors/jquery/jquery-1.12.0.min.js:3:18871)
    at n.fn.init.a.fn.(anonymous function) [as hashchange] (http://localhost:6681/musicbox_webclient/vendors/jquery_mobile/jquery.mobile-1.3.2.min.js:2:13015)
    at HTMLDocument.<anonymous> (http://localhost:6681/musicbox_webclient/js/gui.js:437:15)
    at i (http://localhost:6681/musicbox_webclient/vendors/jquery/jquery-1.12.0.min.js:2:27451)
    at Object.fireWith [as resolveWith] (http://localhost:6681/musicbox_webclient/vendors/jquery/jquery-1.12.0.min.js:2:28215)
    at Function.ready (http://localhost:6681/musicbox_webclient/vendors/jquery/jquery-1.12.0.min.js:2:30008)
    at HTMLDocument.K (http://localhost:6681/musicbox_webclient/vendors/jquery/jquery-1.12.0.min.js:2:30370)
```
Steps to reproduce:
* Navigate to an Artist or Album listing by selecting "Show artist"/"Show album" from the popup menu or from the search results.
* Refresh the page

Have not looked to see when this was introduced. Not sure of the best way to fix it either.  My first guess would be to track the connection state via an `isConnected` variable and check it before trying to access `mopidy.library` in `showArtist` and `showAlbum`. There is probably a more elegant way...

### PR DESCRIPTION
**Pull request by jcass77**
Not sure if this is the most elegant fix.

When the user clicks the browser's 'Refresh' button ``$(document).ready()`` will re-initialize everything. This includes a [call to ``onHashChange()``](https://github.com/jcass77/Mopidy-MusicBox-Webclient/blob/e3eddf2e288d343ed0fe51f18bd619ee616f5bbd/mopidy_musicbox_webclient/static/js/gui.js#L444). 

By the same token ``onHashChange()`` is also called when the [socket connection is established](https://github.com/jcass77/Mopidy-MusicBox-Webclient/blob/e3eddf2e288d343ed0fe51f18bd619ee616f5bbd/mopidy_musicbox_webclient/static/js/gui.js#L208).

So it is probably safe to ignore all ``onHashChange()`` calls until the ``mopidy`` object has been initialized.

Fixes #230.

### CODE REVIEW

**Comment by jcass77** [comment]
...merged with upstream/develop.

**Comment by kingosticks** [comment]
I originally tried to hack a fix for this in the library methods themselves so we could leave `locationHashChanged` to run through and do whatever other styling stuff it's doing. But I'm happy enough that if you cannot connect to the websocket then who cares about any style inconsistencies, you've got bigger problems.

**Comment by jcass77** [comment]
I've pushed 9384e69dd428189edd8c97ebe396f463a1c00d2b which I think is a little better.

It will process all of the case statements that we do not need a Mopidy object for, and also shows the offline notification until the page refresh is completed.

**Comment by jcass77** [comment]
I've pushed 65b58a935219f27c501befc71b996f2e5bfcaf3e, which resolves merge conflicts with upstream/develop.

@kingosticks, any other comments before we merge?

**Pull request merged**
